const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");global.window=global;let saved=null;global.localStorage={getItem:()=>saved,setItem:(k,v)=>{saved=v;}};const root=path.resolve(__dirname,".."),load=f=>vm.runInThisContext(fs.readFileSync(path.join(root,f),"utf8"),{filename:f});[
"js/config.js","js/engine/vector.js","js/engine/random.js","js/data/characterClasses.js","js/data/characterRarities.js","js/data/characterTags.js","js/data/characterBalance.js","js/data/physicsPresets.js","js/data/arenaDefinitions.js","js/characters/CharacterBase.js","js/characters/CharacterRegistry.js","js/powers/PowerRegistry.js","js/powers/temporalPowers.js","js/powers/clonePoisonPowers.js","js/powers/kineticDefensivePowers.js","js/powers/gravityElementalPowers.js","js/powers/arenaChaosPowers.js","js/data/charactersAlpha.js","js/data/charactersBeta.js","js/data/charactersGamma.js","js/data/charactersDelta.js","js/data/charactersEpsilon.js","js/characters/CharacterAI.js","js/data/weapons.js","js/data/perks.js","js/data/abilities.js","js/entities/fighter.js","js/entities/projectile.js","js/characters/CharacterFactory.js","js/characters/CharacterMechanics.js","js/abilities/summonAbilities.js","js/abilities/temporalAbilities.js","js/abilities/elementalAbilities.js","js/abilities/controlAbilities.js","js/abilities/defensiveAbilities.js","js/abilities/offensiveAbilities.js","js/abilities/chaosAbilities.js","js/abilities/expansionCharacterAbilities.js","js/engine/collision.js","js/engine/particles.js","js/storage.js","js/systems/battleLogger.js","js/systems/combatSystem.js","js/systems/projectileSystem.js","js/systems/abilitySystem.js","js/systems/characterBalanceSystem.js","js/systems/matchupSystem.js","js/systems/timeSystem.js","js/systems/summonSystem.js","js/systems/cloneSystem.js","js/systems/poisonSystem.js","js/systems/spikeSystem.js","js/systems/powerSystem.js","js/systems/characterSystem.js","js/systems/arenaSystem.js","js/engine/physics.js","js/systems/characterSimulationSystem.js","js/systems/contentValidationSystem.js"].forEach(load);const OA=global.OrbArena;
assert.equal(OA.CharacterRegistry.all().length,110);assert.equal(new Set(OA.CharacterRegistry.all().map(x=>x.id)).size,110);assert.equal(OA.PowerRegistry.all().length,50);assert.equal(new Set(OA.PowerRegistry.all().map(x=>x.id)).size,50);assert.deepEqual(OA.CharacterMechanics.validate(),[]);assert.deepEqual(OA.PowerRegistry.validate(),[]);
assert.equal(OA.ContentValidationSystem.validate().valid,true);
for(const c of OA.CharacterRegistry.all()){assert.ok(c.id&&c.name&&c.class&&c.rarity);assert.ok(c.kit.active&&c.kit.passive&&c.kit.reactive&&c.kit.ultimate);assert.ok(Object.values(c.stats).every(v=>typeof v!=="number"||Number.isFinite(v)&&v>=0));assert.ok(OA.CHARACTER_RARITIES[c.rarity]);if(c.createdAt>=60)assert.ok(OA.PowerRegistry.get(c.powerId),`${c.id} sem poder`);}
for(const p of OA.PowerRegistry.all()){assert.ok(p.cooldown>=OA.CHARACTER_LIMITS.maxCooldownFloor);assert.ok(p.duration>=0&&p.powerBudget>0);assert.ok(p.tags.length&&typeof p.activate==="function"&&typeof p.update==="function");}
const noop=()=>0,context={damage:noop,heal:noop,shield:noop,impulse:noop,radial:noop,projectile:noop,burst:noop,zone:noop,summon:()=>({active:true,x:300,y:270}),clone:()=>({active:true,x:300,y:270,health:20}),poison:noop,poisonPool:noop,spikes:noop,slowFighter:noop,slowProjectiles:noop,slowAbilities:noop,slowGame:noop,slowVisual:noop,slowEffect:noop,slowAnimation:noop,teleport:(w,a,x,y)=>{a.x=x;a.y=y;},clearControls:noop,removeProjectiles:()=>2,addOrbitals:noop,schedule:(w,d,a)=>w.scheduled.push({delay:d,action:a}),effect:(w,e)=>w.effects.push(e)};
for(const p of OA.PowerRegistry.all()){const actor=OA.CharacterFactory.create(OA.CharacterRegistry.get("afterimage"),{id:"a",team:"player",x:350,y:270,vx:200,vy:0,orbit:1,phase:0}),target=OA.CharacterFactory.create(OA.CharacterRegistry.get("anchor"),{id:"b",team:"enemy",x:520,y:270,vx:-150,vy:0,orbit:-1,phase:1}),world={player:actor,enemy:target,time:1,arena:{centerX:480,centerY:270,radius:238,shape:"circle",portals:[]},summons:[],effects:[],scheduled:[],characterZones:[],poisonPools:[]};assert.doesNotThrow(()=>p.activate({world,actor,target,context,random:new OA.Random(p.id),power:p}),p.id);}
const silent={emitImpact(){},emitShockwave(){},emitWallImpact(){},emitAbility(){},emitText(){}},audio={wall(){},ability(){}};const arenaSystem=new OA.ArenaSystem(new OA.Random("ARENA"),silent,audio),arena=arenaSystem.create("arcade","reactor"),fighter=OA.CharacterFactory.create(OA.CharacterRegistry.get("anchor"),{id:"circle",team:"player",x:900,y:270,vx:500,vy:0,orbit:1,phase:0}),physics=new OA.PhysicsSystem(new OA.Random("PHYS"),{handleWallImpact(){}},{pool:[]}),world={arena,physics:OA.getPhysicsPreset("arcade")};physics.resolveWalls(world,fighter);assert.ok(Math.hypot(fighter.x-arena.centerX,fighter.y-arena.centerY)<=arena.radius-fighter.radius+.001);assert.ok(fighter.vx<0,"ricochete circular alternativo precisa refletir para dentro");
saved=JSON.stringify({settings:{audio:false},history:[]});const storage=new OA.Storage("test");const migrated=storage.read();assert.equal(migrated.saveVersion,3);assert.equal(migrated.settings.audio,false);assert.ok(Array.isArray(migrated.builds)&&migrated.migrationLog.length===1);
const time=new OA.TimeSystem(),tw={};time.slowFighter("enemy",.2,2,null);time.slowEffect(.3,2,null);time.update(tw,.1);assert.equal(tw.timeScales.fighter.enemy,.2);assert.equal(tw.timeScales.effect,.3);assert.ok("animation" in tw.timeScales);
const balance=new OA.CharacterBalanceSystem(),matchups=new OA.MatchupSystem(),sim=new OA.CharacterSimulationSystem(balance,matchups),report=sim.simulate(OA.CharacterRegistry.get("afterimage"),OA.CharacterRegistry.get("quasar"),100,"FIXED");assert.equal(report.count,100);assert.ok(report.rate>=0&&report.rate<=100);assert.equal(balance.audit.length,110);
const html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"css/expansion.css"),"utf8"),ui=fs.readFileSync(path.join(root,"js/ui/characterSelectUI.js"),"utf8");assert.match(html,/character-pagination/);assert.match(html,/screen-powers/);assert.match(ui,/pageSize=24/);assert.match(css,/@media\(max-width:650px\)/);console.log("EXPANSION_OK",{characters:110,powers:50,mechanics:OA.CharacterMechanics.handlers.size,budgets:balance.audit.length,saveVersion:migrated.saveVersion});
