(function () {
  "use strict";
  const OA = window.OrbArena, esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
  const definitions = {
    arsenal: { number: "07", rank: "II", title: "ARSENAL", description: "Armas, alcance, dano, compatibilidade e comparação.", kind: "weapons" },
    perks: { number: "08", rank: "III", title: "PERKS", description: "Modificadores, conflitos e desempenho nas builds.", kind: "perks" },
    abilities: { number: "09", rank: "III", title: "HABILIDADES", description: "Técnicas ativas, reativas, ultimates e poderes registrados.", kind: "abilities" }
  };
  class CatalogUI {
    constructor(app) { this.app = app; this.compare = { weapons: [], perks: [], abilities: [] }; Object.entries(definitions).forEach(([id, def]) => this.ensure(id, def)); }
    ensure(id, def) { document.querySelector(".screen-stack").insertAdjacentHTML("beforeend", `<section class="screen module-screen" id="screen-${id}"><div class="module-page"><header class="module-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">${def.number} · CATÁLOGO TÁTICO · ${def.rank}</span><h1>${def.title}</h1><p>${def.description}</p></div></header><div class="module-toolbar"><input type="search" data-search placeholder="Buscar por nome, ID ou tag…"><select data-category><option value="">Todas as categorias</option></select><select data-rarity><option value="">Todas as raridades</option></select><select data-lock><option value="">Todos os estados</option><option value="unlocked">Desbloqueados</option><option value="favorite">Favoritos</option></select><select data-sort><option value="name">Nome</option><option value="budget">Power Budget</option><option value="damage">Dano</option><option value="cooldown">Cooldown</option></select></div><div class="module-split"><div><div class="catalog-grid" data-list></div><nav class="module-pagination"><button data-prev>←</button><span data-page>1 / 1</span><button data-next>→</button></nav></div><aside class="panel module-detail" data-detail><div class="empty-state">Selecione um item para ver detalhes e ações.</div></aside></div></div></section>`); const screen = document.querySelector(`#screen-${id}`); screen.dataset.page = "1"; screen.querySelector("[data-go-home]").onclick = () => app.goHome(); screen.querySelectorAll("input,select").forEach((element) => element.oninput = () => { screen.dataset.page = "1"; this.render(id); }); screen.querySelector("[data-prev]").onclick = () => { screen.dataset.page = String(Math.max(1, Number(screen.dataset.page)-1)); this.render(id); }; screen.querySelector("[data-next]").onclick = () => { screen.dataset.page = String(Number(screen.dataset.page)+1); this.render(id); }; }
    open(id, selected = null) { this.render(id); this.app.showScreen(id); if (selected) this.detail(id, selected); }
    render(id) { const def = definitions[id], screen = document.querySelector(`#screen-${id}`), data = OA.CATALOG[def.kind], search = screen.querySelector("[data-search]").value.toLowerCase(), category = screen.querySelector("[data-category]").value, rarity = screen.querySelector("[data-rarity]").value, lock = screen.querySelector("[data-lock]").value, favorites = new Set(this.app.storage.read().favorites[def.kind] || []); if (!screen.dataset.filtersReady) { const categories=[...new Set(data.map((item)=>item.category||item.type).filter(Boolean))].sort(), rarities=[...new Set(data.map((item)=>item.rarity).filter(Boolean))]; screen.querySelector("[data-category]").insertAdjacentHTML("beforeend",categories.map((item)=>`<option>${esc(item)}</option>`).join(""));screen.querySelector("[data-rarity]").insertAdjacentHTML("beforeend",rarities.map((item)=>`<option>${esc(item)}</option>`).join(""));screen.dataset.filtersReady="true"; }
      let list = data.filter((item) => `${item.name} ${item.id} ${(item.tags||[]).join(" ")}`.toLowerCase().includes(search) && (!category || (item.category||item.type)===category) && (!rarity || item.rarity===rarity) && (lock!=="favorite" || favorites.has(item.id)) && (lock!=="unlocked" || item.unlocked!==false)); const sort=screen.querySelector("[data-sort]").value; list.sort((a,b)=>sort==="budget"?(b.powerBudget||0)-(a.powerBudget||0):sort==="damage"?(b.damage||0)-(a.damage||0):sort==="cooldown"?(a.cooldown||0)-(b.cooldown||0):a.name.localeCompare(b.name)); const size=24,pages=Math.max(1,Math.ceil(list.length/size)),page=Math.min(pages,Number(screen.dataset.page)||1);screen.dataset.page=String(page);screen.querySelector("[data-page]").textContent=`${page} / ${pages}`;list=list.slice((page-1)*size,page*size);screen.querySelector("[data-list]").innerHTML=list.length?list.map((item)=>`<article class="panel catalog-card" data-id="${item.id}"><small>${favorites.has(item.id)?"★ ":""}${esc(item.rarity)} · ${esc(item.category||item.type)}</small><h2>${esc(item.name)}</h2><p>${esc(item.description||item.effect||item.tags.join(" · "))}</p><div><span>${item.powerBudget||0} PB</span>${item.damage!==undefined?`<span>${Math.round(item.damage)} dano</span>`:""}${item.cooldown!==undefined?`<span>${item.cooldown}s</span>`:""}</div></article>`).join(""):'<div class="panel empty-state"><h2>Nenhum item encontrado.</h2><p>Ajuste os filtros para ampliar os resultados.</p></div>';screen.querySelectorAll("[data-id]").forEach((card)=>card.onclick=()=>this.detail(id,card.dataset.id)); }
    detail(id,itemId){const def=definitions[id],item=OA.catalogById(def.kind,itemId),host=document.querySelector(`#screen-${id} [data-detail]`);if(!item)return;const current=this.app.state.currentBuild,used=this.app.storage.listBuilds().filter((build)=>build.weaponId===item.id||build.perks.includes(item.id)||Object.values(build.abilities).includes(item.id));host.innerHTML=`<small>${esc(item.id)} · ${esc(item.rarity)}</small><h2>${esc(item.name)}</h2><p>${esc(item.description||item.effect)}</p>${def.kind==="weapons"?`<div class="weapon-preview"><i style="--weapon:${item.color};--range:${Math.min(90,item.range/4)}%"></i><b></b></div>`:""}<dl>${Object.entries(def.kind==="weapons"?{Categoria:item.category,Dano:item.damage,DPS:item.dps,Alcance:item.range,Velocidade:item.speed,Cooldown:item.cooldown,Knockback:item.knockback,Crítico:`${item.critical}%`,Efeito:item.effect,"Tipo de dano":item.damageType}:def.kind==="perks"?{Categoria:item.category,Efeito:item.effect,Desvantagem:item.downside,"Power Budget":item.powerBudget,Sinergias:item.synergies.join(", "),Incompatibilidades:item.conflicts.join(", ")||"Nenhuma"}:{Tipo:item.type,Categoria:item.category,Cooldown:item.cooldown,Duração:item.duration,Alcance:item.range||0,Dano:item.damage,Controle:item.control,Mobilidade:item.mobility,"Power Budget":item.powerBudget,Counters:(item.counters||[]).join(", ")}).map(([key,value])=>`<dt>${esc(key)}</dt><dd>${esc(value)}</dd>`).join("")}</dl><p>Usada em ${used.length} build(s).</p><div class="detail-actions"><button data-action="add">Adicionar à build</button><button data-action="favorite">Favoritar</button><button data-action="compare">Comparar</button><button data-action="test">Testar</button>${def.kind==="weapons"?'<button data-action="characters">Personagens compatíveis</button>':''}</div><div data-compare-result></div>`;host.querySelectorAll("[data-action]").forEach((button)=>button.onclick=()=>this.action(id,item,button.dataset.action,host));}
    action(id,item,action,host){const kind=definitions[id].kind;if(action==="add"){const build=this.app.state.currentBuild||this.app.buildSystem.create();if(kind==="weapons")build.weaponId=item.id;else if(kind==="perks"){if(!build.perks.includes(item.id)&&build.perks.length<4)build.perks.push(item.id);else if(build.perks.length>=4)return this.app.toast("Limite de 4 perks.","error");}else {const slot=item.type==="Reativa"?"reactive":item.type==="Ultimate"?"ultimate":item.type==="Passiva"?"passive":build.abilities.active?"secondary":"active";build.abilities[slot]=item.id;}this.app.state.currentBuild=build;this.app.toast(`${item.name} adicionado à build.`);}else if(action==="favorite"){this.app.storage.toggleFavorite(kind,item.id);this.render(id);this.app.toast("Favorito atualizado.");}else if(action==="compare"){const list=this.compare[kind];if(!list.includes(item.id))list.push(item.id);if(list.length>2)list.shift();if(list.length===2){const [a,b]=list.map((value)=>OA.catalogById(kind,value));host.querySelector("[data-compare-result]").innerHTML=`<h3>COMPARAÇÃO</h3><table><tr><th>${esc(a.name)}</th><th>${esc(b.name)}</th></tr><tr><td>${a.powerBudget} PB</td><td>${b.powerBudget} PB</td></tr><tr><td>${a.damage||a.cooldown||a.category}</td><td>${b.damage||b.cooldown||b.category}</td></tr></table>`;}else this.app.toast("Escolha mais um item para comparar.");}else if(action==="test"){const build=this.app.state.currentBuild||this.app.buildSystem.create();if(kind==="weapons")build.weaponId=item.id;if(kind==="abilities"&&item.source==="core")build.abilities.active=item.id;this.app.buildUI.open(build);this.app.buildUI.action("test");}else if(action==="characters"){host.querySelector("[data-compare-result]").innerHTML=`<h3>COMPATÍVEIS</h3><p>${item.compatibleCharacters.map((char)=>OA.CharacterRegistry.get(char)?.name).filter(Boolean).join(", ")||"Compatível com todas as classes."}</p>`;}}
  }
  OA.CatalogUI=CatalogUI;
}());
