(function(){
  "use strict";const OA=window.OrbArena,esc=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  class HomeRemasterUI{
    constructor(app){this.app=app;this.ensure();this.bindGlobalFeedback();this.render();}
    ensure(){const actions=document.querySelector(".primary-actions"),abilityCount=OA.CATALOG?.abilities?.length||OA.ABILITIES?.length||0;actions.insertAdjacentHTML("afterend",`<section class="home-command" aria-label="Central de comando"><div class="home-command-head"><div><small>CONTINUAR OPERAÇÃO</small><h2>PAINEL DO OPERADOR</h2></div><button class="button button-secondary" data-home-continue>CONTINUAR →</button></div><div class="home-command-grid"></div><nav class="home-shortcuts" aria-label="Atalhos"><button data-home-action="draft"><b>09</b><span>Draft completo</span></button><button data-home-action="abilities"><b>${abilityCount}</b><span>Habilidades</span></button><button data-home-action="visual-lab"><b>FX</b><span>Laboratório visual</span></button><button data-home-action="history"><b>REC</b><span>Histórico</span></button></nav></section>`);
      document.body.insertAdjacentHTML("beforeend",`<nav class="mobile-dock" aria-label="Navegação móvel"><button data-dock="menu"><b>⌂</b>Home</button><button data-dock="draft"><b>◇</b>Draft</button><button data-dock="abilities"><b>✦</b>Skills</button><button data-dock="builds"><b>▣</b>Builds</button><button data-dock="settings"><b>⚙</b>Ajustes</button></nav><div class="audio-caption" role="status" aria-live="polite"></div>`);
      this.root=document.querySelector(".home-command");this.root.querySelector("[data-home-continue]").onclick=()=>this.continue();this.root.querySelectorAll("[data-home-action]").forEach((button)=>button.onclick=()=>this.action(button.dataset.homeAction));document.querySelectorAll("[data-dock]").forEach((button)=>button.onclick=()=>this.action(button.dataset.dock));
      const menu=document.querySelector("#screen-menu");menu.addEventListener("pointermove",(event)=>{if(this.app.state.settings.reducedMotion)return;const rect=menu.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width-.5,y=(event.clientY-rect.top)/rect.height-.5;menu.style.setProperty("--parallax-x",`${x*10}px`);menu.style.setProperty("--parallax-y",`${y*7}px`);},{passive:true});
    }
    render(){const data=this.app.storage.read(),build=data.builds[0],battle=data.history[0],favoriteId=data.favorites?.bestiary?.[0]||data.settings.characterId||"echo",character=OA.CharacterRegistry.get(favoriteId)||OA.CharacterRegistry.get("echo"),achievement=OA.ACHIEVEMENTS?.find((item)=>data.achievements.includes(item.id)),arena=Object.values(OA.ARENA_DEFINITIONS)[(data.history.length+data.builds.length)%Object.values(OA.ARENA_DEFINITIONS).length];
      this.root.querySelector(".home-command-grid").innerHTML=`<button data-card="build"><small>ÚLTIMA BUILD</small><b>${esc(build?.name||"Crie sua primeira build")}</b><span>${esc(build?`${build.characterId} · ${build.weaponId}`:"Monte um loadout persistente")}</span></button><button data-card="character" style="--accent:${character.color}"><small>ORB FAVORITA</small><b>${esc(character.name)}</b><span>${esc(character.class)} · ${esc(character.rarity)}</span></button><button data-card="history"><small>PARTIDA RECENTE</small><b>${battle?`${battle.winnerTeam==="player"||battle.winner==="player"?"VITÓRIA":"DERROTA"} · ${Math.round(battle.duration||0)}s`:"Nenhum registro"}</b><span>${esc(battle?.mode||"Entre na arena")}</span></button><button data-card="achievement"><small>CONQUISTA RECENTE</small><b>${esc(achievement?.name||"Primeira Vitória")}</b><span>${esc(achievement?.description||"Sua próxima conquista está pronta")}</span></button><button data-card="arena"><small>ARENA RECOMENDADA</small><b>${esc(arena.name)}</b><span>Retangular · Wall Boost ativo</span></button><button data-card="update"><small>ATUALIZAÇÃO ATUAL</small><b>DESIGN & ABILITY OVERHAUL</b><span>Orbs, telegraphs, ícones e laboratório visual</span></button>`;
      this.root.querySelectorAll("[data-card]").forEach((button)=>button.onclick=()=>this.card(button.dataset.card,{build,battle,character,arena}));
    }
    continue(){const data=this.app.storage.read(),build=data.builds[0];if(build)this.app.startBattle(structuredClone(build),"normal",OA.Random.createSeed(),OA.getPhysicsPreset(build.physicsPreset||"arcade"),{arenaId:build.arenaId,durationPreset:build.durationPreset});else this.app.draftUI.open();}
    action(action){if(action==="menu")return this.app.goHome();if(action==="draft")return this.app.draftUI.open();if(action==="visual-lab")return this.app.visualLabUI.open();this.app.navigate(action);}
    card(type,data){if(type==="build")return data.build?this.app.buildUI.open(data.build):this.app.buildUI.open();if(type==="character")return this.app.openCharacterSelect();if(type==="history")return this.app.archiveUI.openHistory(data.battle?.id);if(type==="arena")return this.app.draftUI.open();if(type==="achievement")return this.app.remasterUI.open("achievements");if(type==="update")return this.app.visualLabUI.open();}
    bindGlobalFeedback(){let hoverAt=0;document.addEventListener("pointerover",(event)=>{if(!event.target.closest("button,[role=button],.catalog-card,.character-card"))return;const now=performance.now();if(now-hoverAt<90)return;hoverAt=now;this.app.audio.interface("hover");});document.addEventListener("click",(event)=>{const target=event.target.closest("button,[role=button]");if(!target)return;this.app.audio.interface(target.classList.contains("button-primary")?"confirm":"select");this.caption(target.getAttribute("aria-label")||target.textContent.trim().replace(/\s+/g," ").slice(0,48));});}
    caption(text){if(!this.app.state.settings.audioCaptions)return;const element=document.querySelector(".audio-caption");element.textContent=`SOM: ${text}`;element.classList.add("visible");clearTimeout(this.captionTimer);this.captionTimer=setTimeout(()=>element.classList.remove("visible"),900);}
  }
  OA.HomeRemasterUI=HomeRemasterUI;
}());
