(function(){
  "use strict";
  const OA=window.OrbArena,esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  class RemasterUI{
    constructor(app){this.app=app;this.ensureFlow();this.ensureNavigation();this.ensureHub();this.ensureReplay();this.ensureTutorial();}
    ensureFlow(){const overlay=document.createElement("div");overlay.className="protocol-flow visible";overlay.innerHTML=`<div class="flow-mark"><i></i><small>DUKE DANDALIAN APRESENTA</small><h1>ORB ARENA</h1><b>CHAOS PROTOCOL // V5</b><span>Inicializando núcleo tático…</span><button>PULAR</button></div>`;document.body.appendChild(overlay);this.flow=overlay;overlay.querySelector("button").onclick=()=>overlay.classList.remove("visible");setTimeout(()=>overlay.classList.remove("visible"),900);}
    matchIntro(world){const teams=world.match?.teams||[];this.flow.querySelector(".flow-mark").innerHTML=`<small>${world.match?.label||"BATALHA"} · ${world.arena.name}</small><h1>${teams.map((team)=>team.label).join(" × ")}</h1><b>${world.fighters.map((fighter)=>fighter.name).join(" · ")}</b><div class="flow-loader"><i></i></div><span>Sincronizando física, IA e ${world.fighters.length} combatentes…</span><button>ENTRAR NA ARENA</button>`;this.flow.classList.add("visible","match-flow");const close=()=>this.flow.classList.remove("visible","match-flow");this.flow.querySelector("button").onclick=close;setTimeout(close,1250);}
    ensureNavigation(){
      document.querySelector("[data-open-draft]").onclick=()=>this.app.draftUI.open();document.querySelectorAll("[data-remaster]").forEach((button)=>button.onclick=()=>this.open(button.dataset.remaster));
      document.querySelector(".stage-card h2").textContent="REMASTER COMERCIAL V5";document.querySelector(".stage-card p").textContent="Draft em 9 etapas, equipes 4v4, controle manual, replay, MVP, conquistas e ferramentas.";
    }
    addScreen(id,html){const section=document.createElement("section");section.className="screen remaster-screen";section.id=`screen-${id}`;section.innerHTML=html;document.querySelector(".screen-stack").appendChild(section);section.querySelectorAll("[data-go-home]").forEach((button)=>button.onclick=()=>this.app.goHome());return section;}
    ensureHub(){
      this.hub=this.addScreen("hub",`<div class="remaster-page"><header class="remaster-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">ARQUIVO DO OPERADOR</span><h1 data-hub-title>PERFIL</h1><p data-hub-subtitle>Progressão local e estatísticas persistentes.</p></div></header><nav class="hub-tabs"><button data-tab="profile">Perfil</button><button data-tab="achievements">Conquistas</button><button data-tab="collection">Coleção</button><button data-tab="compare">Comparador</button></nav><div class="hub-content"></div></div>`);
      this.hub.querySelectorAll("[data-tab]").forEach((button)=>button.onclick=()=>this.renderHub(button.dataset.tab));
    }
    open(type){if(type==="replays")return this.openReplays();if(type==="tutorial")return this.openTutorial();this.app.showScreen("hub");this.renderHub(type==="collection"?"collection":type||"profile");}
    renderHub(tab){const data=this.app.storage.read(),content=this.hub.querySelector(".hub-content");this.hub.querySelectorAll("[data-tab]").forEach((b)=>b.classList.toggle("active",b.dataset.tab===tab));
      if(tab==="profile"){const p=data.profile,needed=Math.pow(p.level,2)*250,progress=Math.min(100,p.xp/needed*100);content.innerHTML=`<div class="profile-hero panel"><div class="profile-emblem">${p.level}</div><div><small>NÍVEL DE OPERADOR</small><h2>DUKE PROTOCOL</h2><p>${p.xp} XP total</p><i><b style="width:${progress}%"></b></i></div></div><div class="metric-grid">${[[p.battles,"Batalhas"],[p.wins,"Vitórias"],[p.losses,"Derrotas"],[p.mvp,"MVP"],[p.wallBounces,"Wall Boosts"],[p.ultimates,"Ultimates"]].map(([v,l])=>`<article class="panel"><strong>${v}</strong><span>${l}</span></article>`).join("")}</div><article class="panel profile-credit"><small>CRÉDITOS PERMANENTES</small><h2>Duke Dandalian</h2><p>Criado, desenvolvido, projetado e dirigido por Duke Dandalian.</p></article>`;return;}
      if(tab==="achievements"){const unlocked=new Set(data.achievements);content.innerHTML=`<div class="collection-grid">${OA.ACHIEVEMENTS.map((item)=>`<article class="panel unlock-card ${unlocked.has(item.id)?"unlocked":"locked"}"><span>${unlocked.has(item.id)?"◆":"◇"}</span><small>${unlocked.has(item.id)?"DESBLOQUEADA":"BLOQUEADA"}</small><h2>${esc(item.name)}</h2><p>${esc(item.description)}</p></article>`).join("")}</div>`;return;}
      if(tab==="collection"){const recent=data.history.slice(0,8);content.innerHTML=`<div class="collection-head panel"><div><small>COLEÇÃO</small><h2>${Object.keys(data.skins).length+data.collection.skins.length} SKINS · ${data.builds.length} BUILDS</h2></div><button class="button button-primary" data-to-compare>COMPARAR BUILDS</button></div><div class="collection-grid">${data.builds.length?data.builds.map((item)=>`<article class="panel collection-card"><div class="mini-orb"></div><small>${esc(item.characterId)}</small><h2>${esc(item.name)}</h2><p>${esc(item.weaponId)} · ${item.perks.length} perks · ${item.winRate}% WR</p></article>`).join(""):`<article class="panel empty-state"><h2>COLEÇÃO PRONTA</h2><p>Salve uma build no editor para adicioná-la aqui.</p></article>`}</div><h2 class="section-caption">PARTIDAS RECENTES</h2><div class="history-strip">${recent.map((item)=>`<span>${esc(item.mode||"duel")} · ${Math.round(item.duration||0)}s</span>`).join("")||"Nenhuma partida registrada."}</div>`;content.querySelector("[data-to-compare]").onclick=()=>this.renderHub("compare");return;}
      const builds=data.builds.length?data.builds:[this.app.menuUI.getBuild()];const options=builds.map((b,i)=>`<option value="${i}">${esc(b.name||b.characterId)}</option>`).join("");content.innerHTML=`<div class="compare-controls panel"><label>BUILD A<select data-compare-a>${options}</select></label><b>VS</b><label>BUILD B<select data-compare-b>${options}</select></label></div><div class="compare-result"></div>`;const render=()=>{const a=builds[+content.querySelector("[data-compare-a]").value]||builds[0],b=builds[+content.querySelector("[data-compare-b]").value]||builds[0],ca=OA.CharacterRegistry.get(a.characterId),cb=OA.CharacterRegistry.get(b.characterId),rows=[["Poder",this.app.balance.get(ca?.id),this.app.balance.get(cb?.id)],["Vida",ca?.stats.health,cb?.stats.health],["Dano",ca?.stats.damage,cb?.stats.damage],["Velocidade",ca?.stats.speed,cb?.stats.speed],["Perks",a.perks?.length||0,b.perks?.length||0],["Win rate",a.winRate||0,b.winRate||0]];content.querySelector(".compare-result").innerHTML=`<div class="compare-names"><h2>${esc(ca?.name||a.name)}</h2><h2>${esc(cb?.name||b.name)}</h2></div>${rows.map(([l,av,bv])=>`<div class="compare-row"><strong class="${av>bv?"winner":""}">${av??"—"}</strong><span>${l}</span><strong class="${bv>av?"winner":""}">${bv??"—"}</strong></div>`).join("")}`;};content.querySelectorAll("select").forEach((select)=>select.onchange=render);if(builds.length>1)content.querySelector("[data-compare-b]").value="1";render();
    }
    ensureReplay(){
      this.replay=this.addScreen("replays",`<div class="remaster-page"><header class="remaster-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">ARQUIVO CINEMÁTICO</span><h1>REPLAYS</h1><p>Linha do tempo, marcadores e inspeção de cada combatente.</p></div></header><div class="replay-layout"><aside class="panel replay-list"></aside><main class="panel replay-player"><canvas width="960" height="540"></canvas><div class="replay-controls"><button data-replay-play>▶</button><input type="range" min="0" max="1" step=".01" value="0"><select data-replay-speed><option value=".5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select><span data-replay-time>00:00</span></div><div class="replay-markers"></div></main></div></div>`);
      this.replayInput=this.replay.querySelector("input");this.replayInput.oninput=()=>this.drawReplay(+this.replayInput.value);this.replay.querySelector("[data-replay-play]").onclick=()=>this.toggleReplay();
    }
    openReplays(){this.stopReplay();const list=this.app.storage.read().replays;this.app.showScreen("replays");this.replay.querySelector(".replay-list").innerHTML=list.length?list.map((item,index)=>`<button data-replay-index="${index}"><b>${esc(item.name)}</b><span>${Math.round(item.duration)}s · ${esc(item.mode)}</span></button>`).join(""):`<div class="empty-state"><h2>SEM REPLAYS SALVOS</h2><p>Após uma batalha, use “Salvar replay” no relatório.</p></div>`;this.replay.querySelectorAll("[data-replay-index]").forEach((button)=>button.onclick=()=>this.loadReplay(list[+button.dataset.replayIndex]));if(list[0])this.loadReplay(list[0]);else this.clearReplay();}
    loadReplay(replay){this.currentReplay=replay;this.replayInput.max=replay.duration;this.replayInput.value=0;this.replay.querySelector(".replay-markers").innerHTML=(replay.markers||[]).map((m)=>`<button style="left:${m.time/replay.duration*100}%" data-marker="${m.time}" title="${esc(m.type)}"></button>`).join("");this.replay.querySelectorAll("[data-marker]").forEach((b)=>b.onclick=()=>{this.replayInput.value=b.dataset.marker;this.drawReplay(+b.dataset.marker);});this.drawReplay(0);}
    clearReplay(){const ctx=this.replay.querySelector("canvas").getContext("2d");ctx.fillStyle="#03070c";ctx.fillRect(0,0,960,540);ctx.fillStyle="#80e8f5";ctx.font="24px sans-serif";ctx.textAlign="center";ctx.fillText("NENHUM REPLAY CARREGADO",480,270);}
    drawReplay(time){const replay=this.currentReplay;if(!replay)return;const sample=OA.ReplaySystem.sample(replay,time),canvas=this.replay.querySelector("canvas"),ctx=canvas.getContext("2d"),sx=canvas.width/replay.arena.width,sy=canvas.height/replay.arena.height;ctx.fillStyle="#02050a";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#225766";ctx.lineWidth=3;ctx.strokeRect(replay.arena.padding*sx,replay.arena.padding*sy,canvas.width-replay.arena.padding*sx*2,canvas.height-replay.arena.padding*sy*2);for(const f of sample.fighters){ctx.globalAlpha=f.alive?1:.2;const g=ctx.createRadialGradient(f.x*sx-6,f.y*sy-6,2,f.x*sx,f.y*sy,f.radius*sx);g.addColorStop(0,"#fff");g.addColorStop(.35,f.color);g.addColorStop(1,"#07101c");ctx.fillStyle=g;ctx.beginPath();ctx.arc(f.x*sx,f.y*sy,Math.max(5,f.radius*sx),0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#dffaff";ctx.font="12px sans-serif";ctx.textAlign="center";ctx.fillText(f.name,f.x*sx,f.y*sy-f.radius*sx-9);}this.replay.querySelector("[data-replay-time]").textContent=`${Math.floor(time/60)}:${(time%60).toFixed(1).padStart(4,"0")}`;}
    toggleReplay(){if(!this.currentReplay)return;if(this.replayTimer)return this.stopReplay();let last=performance.now();this.replayTimer=setInterval(()=>{const now=performance.now(),speed=+this.replay.querySelector("[data-replay-speed]").value;last=now;const next=+this.replayInput.value+(now-last+50)/1000*speed;if(next>=this.currentReplay.duration){this.replayInput.value=this.currentReplay.duration;this.drawReplay(this.currentReplay.duration);this.stopReplay();return;}this.replayInput.value=next;this.drawReplay(next);},50);this.replay.querySelector("[data-replay-play]").textContent="Ⅱ";}
    stopReplay(){if(this.replayTimer)clearInterval(this.replayTimer);this.replayTimer=null;this.replay?.querySelector("[data-replay-play]")&&(this.replay.querySelector("[data-replay-play]").textContent="▶");}
    ensureTutorial(){this.tutorial=this.addScreen("tutorial",`<div class="remaster-page tutorial-page"><header class="remaster-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">SIMULAÇÃO GUIADA</span><h1>TUTORIAL</h1><p>Domine movimento, habilidades e Wall Boost.</p></div></header><div class="tutorial-track"><article class="panel active"><b>01</b><h2>LEIA A ARENA</h2><p>As Orbs conservam momento. Paredes devolvem energia e podem ativar Wall Boost.</p></article><article class="panel"><b>02</b><h2>CONTROLE</h2><p>Q, W, E e R usam as quatro skills. F dispara a Ultimate quando a carga chega a 100%.</p></article><article class="panel"><b>03</b><h2>AUTOCAST</h2><p>AUTO controla tudo; PLAYER entrega o kit a você; MIXED permite automatizar habilidade por habilidade.</p></article><article class="panel"><b>04</b><h2>VENCER</h2><p>Elimine todos os times hostis antes do limite ou lidere em vida e eliminações.</p></article></div><button class="button button-primary tutorial-launch">INICIAR LAB GUIADO →</button></div>`);this.tutorial.querySelector(".tutorial-launch").onclick=()=>{this.app.state.settings.tutorialCompleted=true;this.app.storage.saveSettings({tutorialCompleted:true});const character=OA.CharacterRegistry.get("echo");this.app.startBattle({characterId:character.id,name:character.name,controlMode:"PLAYER"},"easy",OA.Random.createSeed(),OA.getPhysicsPreset("arcade"),{mode:"lab",enemyCharacterId:"singularity"});};}
    openTutorial(){this.app.showScreen("tutorial");}
  }
  OA.RemasterUI=RemasterUI;
}());
