(function(){
  "use strict";const OA=window.OrbArena;
  class SettingsUI{
    constructor(app){
      this.app=app;this.defaults={quality:"high",visualPreset:"balanced",particleQuality:"medium",durationPreset:"standard",targetFps:60,controlMode:"AUTO",effectsVolume:.8,musicVolume:.55,uiVolume:.7,keybinds:{skill1:"q",skill2:"w",skill3:"e",skill4:"r",ultimate:"f",defensive:" "},trails:true,glow:true,bloom:false,animatedBackground:true,arenaPreview:true,reducedMotion:false,reducedParticles:false,screenShake:true,freezeFrame:true,slowMotion:true,decals:true,distortion:false,shadows:true,lighting:true,statusEffects:true,adaptiveEffects:true,highContrast:false,largeText:false,reducedFlashes:false,colorblind:"none",uiScale:1};
      app.state.settings={...this.defaults,...app.state.settings,keybinds:{...this.defaults.keybinds,...(app.state.settings.keybinds||{})}};this.ensureAdvanced();this.bind();this.apply();
    }
    ensureAdvanced(){document.querySelector(".settings-grid").insertAdjacentHTML("beforeend",`<section class="panel advanced-settings"><h2>CONTROLE & ÁUDIO</h2><label>Modo padrão<select data-advanced="controlMode"><option>AUTO</option><option>PLAYER</option><option>MIXED</option></select></label><label>Limite de FPS<select data-advanced="targetFps"><option value="30">30 FPS</option><option value="60">60 FPS</option><option value="120">120 FPS</option><option value="unlimited">Sem limite</option></select></label><label>Efeitos <input type="range" min="0" max="1" step=".05" data-advanced="effectsVolume"></label><label>Música <input type="range" min="0" max="1" step=".05" data-advanced="musicVolume"></label><label>Interface <input type="range" min="0" max="1" step=".05" data-advanced="uiVolume"></label><h3>ATALHOS</h3><div class="keybind-grid">${[["skill1","Skill 1"],["skill2","Skill 2"],["skill3","Skill 3"],["skill4","Skill 4"],["ultimate","Ultimate"]].map(([id,label])=>`<label>${label}<input maxlength="1" data-keybind="${id}"></label>`).join("")}</div><small>Gamepad: A/X/Y/B para skills e RB para Ultimate.</small></section>`);}
    bind(){
      const quality=document.querySelector("#graphics-quality"),visual=document.querySelector("#visual-preset"),particles=document.querySelector("#particle-quality");
      quality.onchange=(e)=>this.set("quality",e.target.value);visual.onchange=(e)=>this.applyPreset(e.target.value);particles.onchange=(e)=>this.set("particleQuality",e.target.value);
      document.querySelectorAll("[data-setting]").forEach((input)=>{input.checked=this.app.state.settings[input.dataset.setting]??input.checked;input.onchange=()=>this.set(input.dataset.setting,input.checked);});
      document.querySelector("#colorblind-mode").onchange=(e)=>this.set("colorblind",e.target.value);document.querySelector("#ui-scale").oninput=(e)=>this.set("uiScale",+e.target.value);
      quality.value=this.app.state.settings.quality;visual.value=this.app.state.settings.visualPreset;particles.value=this.app.state.settings.particleQuality;document.querySelector("#colorblind-mode").value=this.app.state.settings.colorblind;document.querySelector("#ui-scale").value=this.app.state.settings.uiScale;
      document.querySelectorAll("[data-advanced]").forEach((input)=>{input.value=this.app.state.settings[input.dataset.advanced];input.oninput=()=>{const key=input.dataset.advanced,value=input.type==="range"?+input.value:input.value;this.set(key,value);if(key.endsWith("Volume"))this.app.audio.setVolume(key.replace("Volume","").replace("effects","effects"),value);};});
      document.querySelectorAll("[data-keybind]").forEach((input)=>{input.value=this.app.state.settings.keybinds[input.dataset.keybind];input.onchange=()=>{const key=input.value.toLowerCase().slice(0,1);if(!key)return;this.app.state.settings.keybinds[input.dataset.keybind]=key;this.app.storage.saveSettings(this.app.state.settings);};});
    }
    set(key,value){this.app.state.settings[key]=value;this.app.storage.saveSettings(this.app.state.settings);this.apply();}
    applyPreset(id){const preset=OA.VISUAL_PRESETS[id]||OA.VISUAL_PRESETS.balanced;Object.assign(this.app.state.settings,preset,{visualPreset:id});this.app.storage.saveSettings(this.app.state.settings);document.querySelector("#particle-quality").value=this.app.state.settings.particleQuality;document.querySelectorAll("[data-setting]").forEach((input)=>{if(input.dataset.setting in this.app.state.settings)input.checked=this.app.state.settings[input.dataset.setting];});this.apply();}
    apply(){const s=this.app.state.settings,root=document.documentElement;root.style.setProperty("--ui-scale",s.uiScale);document.body.classList.toggle("reduced-motion",s.reducedMotion);document.body.classList.toggle("reduced-particles",s.reducedParticles);document.body.classList.toggle("high-contrast",s.highContrast);document.body.classList.toggle("large-text",s.largeText);document.body.classList.toggle("reduced-flashes",s.reducedFlashes);document.body.classList.toggle("no-glow",!s.glow);document.body.dataset.colorblind=s.colorblind;document.body.dataset.quality=s.quality;document.body.dataset.visualPreset=s.visualPreset;}
  }
  OA.SettingsUI=SettingsUI;
}());
