(function(){
  "use strict";
  const OA=window.OrbArena;
  class ToolsUI{
    constructor(app){this.app=app;this.obstacles=[];this.ensureNav();this.ensureSandbox();this.ensureEditor();this.ensureBattleTools();}
    ensureNav(){const rail=document.querySelector(".menu-rail nav:last-of-type");rail.insertAdjacentHTML("beforeend",`<button class="nav-item" data-tool="sandbox"><span>16</span> Sandbox</button><button class="nav-item" data-tool="editor"><span>17</span> Editor de arena</button>`);document.querySelectorAll("[data-tool]").forEach((b)=>b.onclick=()=>this.open(b.dataset.tool));}
    screen(id,html){const section=document.createElement("section");section.className="screen remaster-screen";section.id=`screen-${id}`;section.innerHTML=html;document.querySelector(".screen-stack").appendChild(section);section.querySelectorAll("[data-go-home]").forEach((b)=>b.onclick=()=>this.app.goHome());return section;}
    ensureSandbox(){this.sandbox=this.screen("sandbox",`<div class="remaster-page"><header class="remaster-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">LABORATÓRIO LIVRE</span><h1>SANDBOX</h1><p>Teste kits com dano, cooldown, IA e tempo ajustáveis.</p></div></header><div class="sandbox-grid"><section class="panel"><h2>COMBATENTE</h2><label>Personagem<select data-sandbox-character></select></label><label>Controle<select data-sandbox-control><option>PLAYER</option><option>MIXED</option><option>AUTO</option></select></label><label>Dificuldade<select data-sandbox-difficulty><option value="easy">Fácil</option><option value="normal" selected>Normal</option><option value="hard">Difícil</option></select></label></section><section class="panel"><h2>REGRAS</h2><label><input type="checkbox" data-sandbox-mod="fast-cooldown"> Cooldown reduzido</label><label><input type="checkbox" data-sandbox-mod="initial-ultimate"> Ultimate inicial</label><label><input type="checkbox" data-sandbox-mod="extreme-wall"> Wall Boost extremo</label><label><input type="checkbox" data-sandbox-mod="hardcore"> Hardcore</label></section><section class="panel sandbox-help"><h2>CONTROLES NO LAB</h2><p>Q/W/E/R: skills · F: Ultimate · Espaço: pausa.</p><p>Durante o teste, o painel inferior permite curar, causar dano, criar clones, limpar cooldowns e aplicar status.</p></section></div><button class="button button-primary sandbox-launch">ABRIR SANDBOX →</button></div>`);this.sandbox.querySelector("[data-sandbox-character]").innerHTML=OA.CharacterRegistry.all().map((c)=>`<option value="${c.id}">${c.name}</option>`).join("");this.sandbox.querySelector(".sandbox-launch").onclick=()=>this.launchSandbox();}
    launchSandbox(){const character=OA.CharacterRegistry.get(this.sandbox.querySelector("[data-sandbox-character]").value),controlMode=this.sandbox.querySelector("[data-sandbox-control]").value,difficulty=this.sandbox.querySelector("[data-sandbox-difficulty]").value,modifiers=[...this.sandbox.querySelectorAll("[data-sandbox-mod]:checked")].map((x)=>x.dataset.sandboxMod);this.app.startBattle({characterId:character.id,name:character.name,controlMode},difficulty,OA.Random.createSeed(),OA.getPhysicsPreset("arcade"),{mode:"lab",matchConfig:{modeId:"1v1",arenaSize:"medium",modifiers}});}
    ensureEditor(){this.editor=this.screen("editor",`<div class="remaster-page"><header class="remaster-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">CONSTRUTOR TÁTICO</span><h1>EDITOR DE ARENA</h1><p>Clique para inserir bumpers; arraste para reposicionar.</p></div></header><div class="editor-layout"><canvas width="960" height="540"></canvas><aside class="panel"><label>Nome<input data-arena-name value="Arena Personalizada"></label><label>Tamanho<select data-arena-size><option value="small">Pequena</option><option value="medium" selected>Média</option><option value="large">Grande</option><option value="huge">Enorme</option></select></label><label>Objeto<select data-object><option value="bumper">Bumper</option><option value="speed">Zona de velocidade</option><option value="power">Power-up</option></select></label><button data-editor-undo>Desfazer</button><button data-editor-clear>Limpar</button><button class="button button-primary" data-editor-save>Salvar arena</button><output></output></aside></div></div>`);const canvas=this.editor.querySelector("canvas");canvas.onclick=(e)=>{const rect=canvas.getBoundingClientRect(),type=this.editor.querySelector("[data-object]").value;this.obstacles.push({type,x:Math.round((e.clientX-rect.left)/rect.width*960),y:Math.round((e.clientY-rect.top)/rect.height*540),radius:type==="speed"?42:25});this.drawEditor();};this.editor.querySelector("[data-editor-undo]").onclick=()=>{this.obstacles.pop();this.drawEditor();};this.editor.querySelector("[data-editor-clear]").onclick=()=>{this.obstacles=[];this.drawEditor();};this.editor.querySelector("[data-editor-save]").onclick=()=>{const result=this.app.storage.saveArena({name:this.editor.querySelector("[data-arena-name]").value,size:this.editor.querySelector("[data-arena-size]").value,shape:"rectangle",obstacles:structuredClone(this.obstacles)});this.editor.querySelector("output").textContent=result.ok?`Arena salva com ${this.obstacles.length} objetos.`:"Falha ao salvar.";};}
    drawEditor(){const canvas=this.editor.querySelector("canvas"),ctx=canvas.getContext("2d");ctx.fillStyle="#03080e";ctx.fillRect(0,0,960,540);ctx.strokeStyle="#3fb8c7";ctx.lineWidth=3;ctx.strokeRect(24,24,912,492);ctx.strokeStyle="rgba(80,190,210,.1)";for(let x=72;x<936;x+=48){ctx.beginPath();ctx.moveTo(x,24);ctx.lineTo(x,516);ctx.stroke();}for(let y=72;y<516;y+=48){ctx.beginPath();ctx.moveTo(24,y);ctx.lineTo(936,y);ctx.stroke();}for(const o of this.obstacles){ctx.fillStyle=o.type==="bumper"?"#ff8a68":o.type==="speed"?"rgba(68,231,244,.3)":"#ba79ef";ctx.beginPath();ctx.arc(o.x,o.y,o.radius,0,Math.PI*2);ctx.fill();} }
    ensureBattleTools(){const controls=document.querySelector(".battle-controls");controls?.insertAdjacentHTML("beforeend",`<button class="control-button" data-photo-mode>◎ FOTO</button><button class="control-button" data-spectator>◇ ESPECTADOR</button><button class="control-button" data-screenshot>▣ CAPTURAR</button>`);document.querySelector("[data-photo-mode]")?.addEventListener("click",(e)=>{const active=document.body.classList.toggle("photo-mode");e.currentTarget.classList.toggle("active",active);this.app.game.setPaused(active,"photo");});document.querySelector("[data-spectator]")?.addEventListener("click",()=>{const w=this.app.game.world;if(!w)return;const allies=w.fighters.filter((f)=>f.teamId==="player"),index=allies.indexOf(w.controlledFighter),next=allies[(index+1)%allies.length];this.app.game.selectControlledFighter(next.id);this.app.toast(`Observando ${next.name}.`);});document.querySelector("[data-screenshot]")?.addEventListener("click",()=>{const canvas=document.querySelector("#arena-canvas"),link=document.createElement("a");link.download=`orb-arena-${Date.now()}.png`;link.href=canvas.toDataURL("image/png");link.click();this.app.toast("Captura criada.");});}
    open(type){if(type==="sandbox")this.app.showScreen("sandbox");else{this.app.showScreen("editor");this.drawEditor();}}
  }
  OA.ToolsUI=ToolsUI;
}());
