(function(){
  "use strict";const OA=window.OrbArena;
  class VisualLabUI{
    constructor(app){this.app=app;this.paused=false;this.hitboxes=false;this.tab="orbs";this.last=0;this.fps=60;this.ensure();}
    ensure(){const section=document.createElement("section");section.className="screen remaster-screen";section.id="screen-visual-lab";section.innerHTML=`<div class="remaster-page visual-lab-page"><header class="remaster-head"><button class="back-button" data-go-home>← MENU</button><div><span class="eyebrow">FERRAMENTA INTERNA</span><h1>VISUAL LAB</h1><p>Inspecione materiais, telegraphs, partículas, componentes e estados sem iniciar uma batalha.</p></div><output data-lab-fps>60 FPS</output></header><div class="visual-lab-toolbar panel"><nav>${["orbs","skills","particles","components","backgrounds"].map((id)=>`<button data-lab-tab="${id}">${id.toUpperCase()}</button>`).join("")}</nav><label>Tema<select data-lab-theme><option value="navy">Navy</option><option value="void">Void</option><option value="contrast">Contraste</option></select></label><label>Resolução<select data-lab-resolution><option value="960x540">960×540</option><option value="1280x720">1280×720</option><option value="390x844">Mobile 390×844</option></select></label><label>Qualidade<select data-lab-quality><option value="performance">Performance</option><option value="balanced" selected>Balanceado</option><option value="cinematic">Cinemático</option></select></label><button data-lab-pause>Ⅱ PAUSAR</button><button data-lab-hitbox>◎ HITBOX</button><button data-lab-export>▣ CAPTURAR</button></div><div class="visual-lab-stage panel" data-theme="navy"><canvas width="960" height="540"></canvas><div class="visual-lab-dom"></div></div><aside class="visual-lab-inspector panel"></aside></div>`;document.querySelector(".screen-stack").appendChild(section);this.root=section;this.canvas=section.querySelector("canvas");this.ctx=this.canvas.getContext("2d");section.querySelector("[data-go-home]").onclick=()=>app.goHome();section.querySelectorAll("[data-lab-tab]").forEach((button)=>button.onclick=()=>{this.tab=button.dataset.labTab;this.renderPanel();});section.querySelector("[data-lab-theme]").onchange=(event)=>section.querySelector(".visual-lab-stage").dataset.theme=event.target.value;section.querySelector("[data-lab-resolution]").onchange=(event)=>this.resolution(event.target.value);section.querySelector("[data-lab-quality]").onchange=(event)=>this.quality=event.target.value;section.querySelector("[data-lab-pause]").onclick=(event)=>{this.paused=!this.paused;event.currentTarget.textContent=this.paused?"▶ CONTINUAR":"Ⅱ PAUSAR";};section.querySelector("[data-lab-hitbox]").onclick=(event)=>{this.hitboxes=!this.hitboxes;event.currentTarget.classList.toggle("active",this.hitboxes);};section.querySelector("[data-lab-export]").onclick=()=>this.capture();this.renderPanel();}
    open(){this.app.showScreen("visual-lab");this.renderPanel();if(!this.running){this.running=true;requestAnimationFrame((time)=>this.frame(time));}}
    resolution(value){const [width,height]=value.split("x").map(Number);this.canvas.width=width;this.canvas.height=height;this.canvas.style.aspectRatio=`${width}/${height}`;this.renderPanel();}
    renderPanel(){this.root.querySelectorAll("[data-lab-tab]").forEach((button)=>button.classList.toggle("active",button.dataset.labTab===this.tab));const dom=this.root.querySelector(".visual-lab-dom"),inspector=this.root.querySelector(".visual-lab-inspector");dom.hidden=["orbs","particles","backgrounds"].includes(this.tab);this.canvas.hidden=!dom.hidden;
      if(this.tab==="skills"){const skills=OA.CATALOG.abilities.slice(0,24);dom.innerHTML=`<div class="lab-skill-grid">${skills.map((skill)=>`<article class="rarity-${OA.AbilityVisualRegistry.className(skill.rarity)}">${OA.skillIconHTML(skill,"ready")}<div><small>${skill.element} · ${skill.rarity}</small><b>${skill.name}</b><span>${skill.cooldown}s · ${skill.charges} carga(s)</span></div></article>`).join("")}</div>`;inspector.innerHTML=`<h2>ICON ATLAS PROCEDURAL</h2><p>Silhuetas derivadas do ID, cor por elemento e estados ready, cooldown, grayscale e Auto Cast sem assets externos.</p>`;}
      else if(this.tab==="components"){dom.innerHTML=`<div class="lab-components"><button class="button button-primary">AÇÃO PRIMÁRIA</button><button class="button button-secondary">SECUNDÁRIA</button><button disabled>DESABILITADO</button><span class="ds-badge">Badge</span><span class="rarity-badge rarity-lendaria">Lendária</span><label>Toggle <input type="checkbox" checked></label><progress value="72" max="100"></progress><div class="ds-loading">Carregando</div><div class="ds-empty">Estado vazio com orientação útil.</div><div class="ds-error">Erro recuperável. Tente novamente.</div><button class="tooltip" data-tooltip="Tooltip acessível e conciso">FOCO / TOOLTIP</button></div>`;inspector.innerHTML=`<h2>ESTADOS DE UI</h2><p>Hover, press, foco, sucesso, erro, loading, vazio e disabled compartilham tokens.</p>`;}
      else {inspector.innerHTML=`<h2>${this.tab.toUpperCase()}</h2><p>${this.tab==="orbs"?"Materiais, runas, núcleo, casca, aura, estados e silhuetas sem alterar hitbox.":this.tab==="particles"?"Pooling e LOD por tipo. A prévia respeita a qualidade selecionada.":"Background procedural de baixo custo, com parallax e contraste controlado."}</p><dl><dt>Qualidade</dt><dd>${this.quality||"balanced"}</dd><dt>Hitboxes</dt><dd>${this.hitboxes?"visíveis":"ocultas"}</dd><dt>Resolução</dt><dd>${this.canvas.width}×${this.canvas.height}</dd></dl>`;}
    }
    frame(time){if(!this.running)return;const active=this.root.classList.contains("active");if(!active){this.running=false;return;}const delta=this.last?Math.min(.1,(time-this.last)/1000):1/60;this.last=time;this.fps+=(1/Math.max(.001,delta)-this.fps)*.08;this.root.querySelector("[data-lab-fps]").textContent=`${Math.round(this.fps)} FPS`;if(!this.paused&&!["skills","components"].includes(this.tab))this.draw(time/1000);requestAnimationFrame((next)=>this.frame(next));}
    draw(time){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);const bg=c.createRadialGradient(w*.5,h*.46,10,w*.5,h*.5,w*.7);bg.addColorStop(0,this.tab==="backgrounds"?"#122334":"#0b1925");bg.addColorStop(1,"#02050a");c.fillStyle=bg;c.fillRect(0,0,w,h);c.strokeStyle="rgba(103,220,229,.06)";for(let x=0;x<w;x+=48){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=48){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}
      if(this.tab==="backgrounds"){c.fillStyle="rgba(103,220,229,.08)";for(let i=0;i<24;i++){const x=(i*193+time*8)%w,y=(i*83)%h;c.fillRect(x,y,2,2);}return;}
      if(this.tab==="particles"){const types=["spark","smoke","ice-shard","toxic-mist","gravity-dust","time-fragment","clone-fragment","shield-fragment"];types.forEach((type,index)=>{const cx=(index%4+.5)*w/4,cy=(Math.floor(index/4)+.5)*h/2,color=["#e7c371","#7f98a3","#91d9e8","#8bcf63","#8b70c9","#7d8ee8","#67cbd7","#70aee1"][index];c.fillStyle=color;c.font=`700 ${Math.max(11,w/80)}px sans-serif`;c.textAlign="center";c.fillText(type.toUpperCase(),cx,cy+58);for(let p=0;p<(this.quality==="performance"?6:14);p++){const a=p*2.399+time*(.4+index*.04),r=15+(p%5)*7;c.globalAlpha=.25+(p%4)*.14;c.beginPath();c.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r,2+(p%3),0,Math.PI*2);c.fill();}c.globalAlpha=1;});return;}
      const chars=["crystal","singularity","inferno","clockwork","venom","prism"].map((id)=>OA.CharacterRegistry.get(id)).filter(Boolean);chars.forEach((character,index)=>{const cols=3,cx=(index%cols+.5)*w/cols,cy=(Math.floor(index/cols)+.55)*h/2,r=Math.min(w/22,h/8),pulse=1+Math.sin(time*2+index)*.035;c.save();c.translate(cx,cy);c.scale(pulse,2-pulse);c.shadowColor=character.glow;c.shadowBlur=this.quality==="performance"?0:14;const g=c.createRadialGradient(-r*.3,-r*.35,2,0,0,r);g.addColorStop(0,"#edfaff");g.addColorStop(.18,character.glow);g.addColorStop(.48,character.color);g.addColorStop(1,"#06101a");c.fillStyle=g;c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle=character.glow;c.lineWidth=2;c.stroke();c.strokeStyle=character.secondary;c.setLineDash([3,5]);c.beginPath();c.arc(0,0,r*.68,time*(index%2?-.3:.3),time*(index%2?-.3:.3)+Math.PI*1.4);c.stroke();c.setLineDash([]);c.fillStyle="#f1fbff";c.font=`700 ${r*.65}px sans-serif`;c.textAlign="center";c.textBaseline="middle";c.fillText(character.icon,0,1);if(this.hitboxes){c.strokeStyle="#fff";c.lineWidth=1;c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.stroke();}c.restore();c.fillStyle="#b7c9d0";c.font=`700 ${Math.max(11,w/75)}px sans-serif`;c.textAlign="center";c.fillText(character.name,cx,cy+r+24);});}
    capture(){const link=document.createElement("a");link.download=`orb-arena-visual-lab-${Date.now()}.png`;link.href=this.canvas.toDataURL("image/png");link.click();this.app.toast("Preview exportada.","success");}
  }
  OA.VisualLabUI=VisualLabUI;
}());
